const levelDatabase = [
    {
        levelName: "Static Symphony",
        folder: "Static Symphony",
        levelIconFile: "level-staticsymphony.png",
        devName: "QAQA",
        devAvatarFile: "dev-qaqa.png",
        publishDate: "2026/7/29",
        songComposer: "EliteFerrex (ft.Sunnexo)",
        soundFile: "staticsymphony.mp3",
        music: true,
        imgpreview: true,
        img: "static_bg.png",
        videoUrl: "https://youtu.be/HzYSUv_zimc?si=ZIuBMIgKv3xGl9ph",
        downloadUrl: "https://drive.google.com/file/d/19X840XCs5Bp4FFAscC9cxR8jaBmX6d3u/view?usp=sharing",
        tagid: "tag01",
        info: "This is QAQA s fisrt JS&B Fanmade Level.",
        stage: "ss.gif"
    },
    {
        levelName: "Ricochet Love",
        folder: "Ricochet Love",
        levelIconFile: "level-ricochetlove.png",
        devName: "Cynastic",
        devAvatarFile: "dev-cynastic.png",
        publishDate: "2025/7/31",
        songComposer: "Waterflame",
        soundFile: "ricochetlove.mp3",
        music: true,
        imgpreview: true,
        img: "rico_bg.png",
        videoUrl: "https://www.bilibili.com/video/BV1Sv8yzwEF4/?",
        downloadUrl: "https://wwha.lanzoub.com/iKvrb328zi8f",
        tagid: "tag02",
        info: "Inspired by Geometry Dash Amethyst",
        stage: ""
    },
    {
        levelName: "PARAGON",
        folder: "PARAGΩN",
        levelIconFile: "level-paragon.png",
        devName: "Ervy",
        devAvatarFile: "dev-ervy.png",
        publishDate: "2025/10/12",
        songComposer: "Titanium Angel",
        soundFile: "paragon.mp3",
        music: true,
        imgpreview: true,
        img: "paragon_bg.png",
        videoUrl: "https://youtu.be/DWen9x48q4k?si=ICskmopiPAJDdFpz",
        downloadUrl: "https://drive.google.com/file/d/1ohXPQzISg4fit3HapB3rVDvX-Hcs0wCE/view?usp=sharing",
        tagid: "tag03",
        info: "[happy-boss]",
        stage: ""
    },
    {
        levelName: "One Forgetten Night",
        folder: "One Forgotten Night",
        levelIconFile: "level-OFN.png",
        devName: "SONGDarkHorse_HeyMA",
        devAvatarFile: "dev-BH.png",
        publishDate: "2026/2/13",
        songComposer: "Quree",
        soundFile: "one_forgotten_night.mp3",
        music: false,
        imgpreview: true,
        img: "ofg.png",
        videoUrl: "https://www.bilibili.com/video/BV1KJZRB3EeR/?",
        downloadUrl: "",
        tagid: "tag04",
        info: "The level created by the Chinese JSAB community for the New Year Festival",
        stage: ""
    },
    {
        levelName: "Eternal Eclipse",
        folder: "Eternal Eclipse",
        levelIconFile: "level-EE.png",
        devName: "NeedSomePractice",
        devAvatarFile: "dev-NSP.png",
        publishDate: "2024/1/12",
        songComposer: "OcularNebula",
        soundFile: "eternaleclipse.mp3",
        music: true,
        imgpreview: true,
        img: "ee_bg.png",
        videoUrl: "https://youtu.be/kqjRQO3g7i8?si=qIw4q7zQSH8sh8Es",
        downloadUrl: "",
        tagid: "tag05",
        info: "",
        stage: ""
    },
    {
        levelName: "Liquid Town",
        folder: "Liquid Town",
        levelIconFile: "level-LT.png",
        devName: "Linkyop",
        devAvatarFile: "dev-Linkyop.png",
        publishDate: "2026/2/15",
        songComposer: "Jason Letourneau",
        soundFile: "Liquid Town.mp3",
        music: true,
        imgpreview: true,
        img: "LT.png",
        videoUrl: "https://youtu.be/TQg1MGWsQAo?si=07yv9gbpXThRJUAJ",
        downloadUrl: "",
        tagid: "tag05",
        info: "OST of infernax level celebrating 4th anniversary",
        stage: ""
    },
    {
        levelName: "SIDStorm",
        folder: "sidstorm",
        levelIconFile: "level-SS.png",
        devName: "Waveboy",
        devAvatarFile: "dev-Waveboy.png",
        publishDate: "2026/2/15",
        songComposer: "LukHash",
        soundFile: "Sid.mp3",
        music: true,
        imgpreview: true,
        img: "SS.png",
        videoUrl: "https://youtu.be/9AeQDTrAvKw?si=lyRo-cBWVzSaHNQE",
        downloadUrl: "",
        tagid: "tag04",
        info: "JSAB special 8th anniversary level",
        stage: ""
    },
    {
        levelName: "ICE POP",
        folder: "ICE POP",
        levelIconFile: "level-pop.png",
        devName: "QAQA﻿",
        devAvatarFile: "dev-qaqa.png",
        publishDate: "2026/7/7",
        songComposer: "SaMZIng",
        soundFile: "",
        music: false,
        imgpreview: true,
        img: "ip_bg.png",
        videoUrl: "https://www.bilibili.com/video/BV1zDM46aEZM/?",
        downloadUrl: "",
        tagid: "none",
        info: "",
        stage: ""
    },
    {
        levelName: "Parallel Processing",
        folder: "Parallel Processing",
        levelIconFile: "level-pp.png",
        devName: "Linkyop﻿",
        devAvatarFile: "dev-linkyop.png",
        publishDate: "2021/12/16",
        songComposer: "Danimal Cannon",
        soundFile: "pp.mp3",
        music: true,
        imgpreview: true,
        img: "PP.png",
        videoUrl: "https://youtu.be/iqsnHXwYnPE?si=o-R8t6x6RPb6cJ2l",
        downloadUrl: "",
        tagid: "tag05",
        info: "",
        stage: ""
    },
    {
        levelName: "Shared Buffer Memory",
        folder: "Shared Buffer Memory",
        levelIconFile: "level-SBM.png",
        devName: "Linkyop  ",
        devAvatarFile: "dev-linkyop.png",
        publishDate: "2024/12/7",
        songComposer: "tiasu",
        soundFile: "SBM.mp3",
        music: true,
        imgpreview: true,
        img: "sbm.png",
        videoUrl: "https://youtu.be/xD-dazVWCaA?si=j4uX6Ut5K8AZjEA-",
        downloadUrl: "",
        tagid: "tag05",
        info: "OST of soundodger 2 (QAQA want to say somthing : i buy the OST TAT)",
        stage: "SBM.gif"
    },
    {
        levelName: "Genocide",
        folder: "Genocide",
        levelIconFile: "level-GNC.png",
        devName: "Linkyop   ",
        devAvatarFile: "dev-linkyop.png",
        publishDate: "2021/6/8",
        songComposer: "Tenzubushi",
        soundFile: "",
        music: false,
        imgpreview: true,
        img: "Genocide.png",
        videoUrl: "https://youtu.be/UNg-7rvY3G0?si=1wovK7wOeQEmldid",
        downloadUrl: "",
        tagid: "tag05",
        info: "OST from Friday Night Funkin vs Tabi mod",
        stage: ""
    },
    {
        levelName: "Camel By Camel",
        folder: "CBC",
        levelIconFile: "level-CBC.png",
        devName: "NeedSomePractice ",
        devAvatarFile: "dev-NSP.png",
        publishDate: "2022/9/4",
        songComposer: "Duzzled (Remix)",
        soundFile: "",
        music: false,
        imgpreview: true,
        img: "CBC.png",
        videoUrl: "https://youtu.be/ljLwbX6Yn7M?si=RRv66M86_lh3T0va",
        downloadUrl: "",
        tagid: "tag05",
        info: "is this meme still alive?[normal]",
        stage: ""
    },
    {
        levelName: "Freakshow",
        folder: "freakshow",
        levelIconFile: "level-F.png",
        devName: " Linkyop   ",
        devAvatarFile: "dev-linkyop.png",
        publishDate: "2021/11/2",
        songComposer: "Skillet",
        soundFile: "",
        music: false,
        imgpreview: true,
        img: "Freakshow.png",
        videoUrl: "https://youtu.be/kPdyFRYB93A?si=CfBQDT629DC68-mz",
        downloadUrl: "",
        tagid: "tag05",
        info: "",
        stage: ""
    },
    {
        levelName: "Hypersynthetic",
        folder: "Hypersynthetic",
        levelIconFile: "level-H.png",
        devName: "Littlewood",
        devAvatarFile: "dev-littlewood.png",
        publishDate: "2025/9/22",
        songComposer: "Akira Complex",
        soundFile: "Hypersynthetic.mp3",
        music: true,
        imgpreview: true,
        img: "HSHS.png",
        videoUrl: "https://www.bilibili.com/video/BV1jcJfzxEtF/?share_source=copy_web&vd_source=ed016cb7178579d295bf5c17eb3a023f",
        downloadUrl: "https://drive.google.com/file/d/1aFOOXKxkRfPoBYyh1BRfGGCms0DSRU5e/view?usp=drive_link",
        tagid: "china",
        info: "Littlewood s level with care",
        stage: ""
    },
    {
        levelName: "APOCALYPTIC",
        folder: "APOCALYPTIC",
        levelIconFile: "level-A.png",
        devName: "Littlewood ",
        devAvatarFile: "dev-littlewood.png",
        publishDate: "2026/3/13",
        songComposer: "Z claxX & Sumailight",
        soundFile: "APOCALYPTIC.mp3",
        music: true,
        imgpreview: true,
        img: "APL.png",
        videoUrl: "https://www.bilibili.com/video/BV1arcUzkEWc?",
        downloadUrl: "https://drive.google.com/file/d/1JQVhkWBrTlGvrYWWsTqsdaVrBasojNYY/view?usp=drive_link",
        tagid: "china",
        info: "MARIO[emm]",
        stage: "blockfall.gif"
    },
    {
        levelName: "Crasy 2",
        folder: "Crazy 2",
        levelIconFile: "level-C.png",
        devName: "N1H1L1TY & NewBieX",
        devAvatarFile: "dev-N.png",
        publishDate: "2026/6/29",
        songComposer: "i forgot...",
        soundFile: "",
        music: false,
        imgpreview: true,
        img: "crazy 2.png",
        videoUrl: "https://youtu.be/C68JvYyLOaw?si=jMBgB3PQY00rpYHs",
        downloadUrl: "https://www.mediafire.com/folder/yo7j279tb58sm/Crazy_2",
        tagid: "tag03",
        info: "JSAB Demonlist Top 1 (2026) [hardcore]",
        stage: ""
    },
    {
        levelName: "Next Level",
        folder: "next level",
        levelIconFile: "level-NL.png",
        devName: "Linkyop     ",
        devAvatarFile: "dev-linkyop.png",
        publishDate: "2021/11/8",
        songComposer: " ‪Avenza",
        soundFile: "",
        music: false,
        imgpreview: true,
        img: "NL.png",
        videoUrl: "https://youtu.be/ZL8wxFxB0go?si=sqsJr7vRE0u84mkz",
        downloadUrl: "",
        tagid: "tag05",
        info: "",
        stage: ""
    },
    {
        levelName: "GOODRAGE",
        folder: "GOODRAGE",
        levelIconFile: "level-G.png",
        devName: "QAQA    ",
        devAvatarFile: "dev-QAQA.png",
        publishDate: "2026/6/29",
        songComposer: "Ebimayo",
        soundFile: "goodrage.mp3",
        music: true,
        imgpreview: true,
        img: "gr.png",
        videoUrl: "",
        downloadUrl: "https://drive.google.com/file/d/1yfMl5onX-6wMATwrNG5W-UMNGdzomm6v/view?usp=drive_link",
        tagid: "tag03",
        info: "I m making this level in rage",
        stage: ""
    }
];